nginx:
    image: nginx
    volumes:
     - nginx:/etc/nginx/conf.d/
    links:
     - goapp
    expose:
     - 80
    ports:
     - "80:80"

goapp:
    build: .
    links:
     - redis

redis:
    image: redis
