nginx:
    image: nginx
    volumes:
     - nginx:/etc/nginx/conf.d/
    links:
     - goapp
    expose:
     - 80
    ports:
     - "80:80"

goapp:
    build: .
    dockerfile: Dockerfile.goapp
    links:
     - redis
     - dynamodb

redis:
    build: .
    dockerfile: Dockerfile.redis
    command: redis-server /code/redis.conf

dynamodb:
    image: tray/dynamodb-local
    command: -inMemory -port 18000
